name: Deploy to App Stores

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "Platform to deploy"
        required: true
        default: "all"
        type: choice
        options:
          - ios
          - android
          - all
      track:
        description: "Deployment track"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - beta
          - alpha
  release:
    types: [published]

env:
  NODE_VERSION: "18"
  EXPO_CLI_VERSION: "latest"

jobs:
  deploy-ios:
    name: Deploy iOS to App Store
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' || github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci
          npx expo install --fix

      - name: Build iOS for App Store
        run: npx eas build --platform ios --profile production --non-interactive

      - name: Submit to App Store
        run: npx eas submit --platform ios --profile production --non-interactive
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Notify Slack on success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "✅ iOS app successfully submitted to App Store!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "❌ iOS app submission to App Store failed!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-android:
    name: Deploy Android to Play Store
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' || github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci
          npx expo install --fix

      - name: Decode Android service account key
        run: |
          echo ${{ secrets.ANDROID_SERVICE_ACCOUNT_KEY_BASE64 }} | base64 -d > android-service-account-key.json

      - name: Build Android for Play Store
        run: npx eas build --platform android --profile production --non-interactive

      - name: Submit to Play Store
        run: npx eas submit --platform android --profile production --non-interactive
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY_PATH: ./android-service-account-key.json

      - name: Clean up service account key
        if: always()
        run: rm -f android-service-account-key.json

      - name: Notify Slack on success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "✅ Android app successfully submitted to Play Store!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "❌ Android app submission to Play Store failed!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-updates:
    name: Deploy OTA Updates
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: ${{ env.EXPO_CLI_VERSION }}
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          npm ci
          npx expo install --fix

      - name: Publish OTA update
        run: npx eas update --auto --non-interactive

      - name: Notify team about OTA update
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "🚀 OTA update published successfully!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
